# Generated by Django 3.2 on 2021-12-30 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Programmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(blank=True, max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=255)),
                ('national_ID_number', models.CharField(blank=True, max_length=255)),
                ('birth_cert_no', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('DOB', models.DateField()),
                ('date_of_admission', models.DateTimeField()),
                ('date_of_graduation', models.DateTimeField()),
                ('postal_address', models.CharField(blank=True, max_length=255)),
                ('school_email', models.EmailField(blank=True, max_length=255)),
                ('school_email_password', models.CharField(blank=True, max_length=255)),
                ('total_fees_billed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fees_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.gender')),
                ('programme', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.programmes')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.stages')),
                ('user', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
