# Generated by Django 3.2 on 2022-01-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20220110_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Units',
        ),
    ]
