# Generated by Django 3.2 on 2022-01-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_delete_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmes',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='students',
            name='programme',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Programmes',
        ),
    ]
