# Generated by Django 3.2 on 2022-01-10 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0008_faculty_gender_programmes_stages_students_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmes',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.faculty'),
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_no', models.CharField(blank=True, max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=255)),
                ('national_ID_number', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('DOB', models.DateField()),
                ('profile_photo', models.ImageField(blank=True, upload_to='lecturer_pic')),
                ('postal_address', models.CharField(blank=True, max_length=255)),
                ('school_email', models.EmailField(blank=True, max_length=255)),
                ('school_email_password', models.CharField(blank=True, max_length=255)),
                ('total_salary_billed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_salary_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.gender')),
                ('user', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
