# Generated by Django 3.2 on 2022-01-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20220110_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
