# Generated by Django 3.2 on 2022-01-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_faculty_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
