# Generated by Django 3.2 on 2022-01-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_faculty_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
