# Generated by Django 3.2 on 2022-01-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20220110_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectures',
            old_name='gender',
            new_name='lec_gender',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='gender',
            new_name='stud_gender',
        ),
    ]
