# Generated by Django 3.2 on 2022-01-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20220113_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='lecturer_pic/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='students_pic/'),
        ),
    ]
