# Generated by Django 3.2 on 2022-01-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20220114_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='DOB',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
