# Generated by Django 3.2 on 2022-01-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20220114_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='DOB',
            field=models.DateTimeField(blank=True),
        ),
    ]
