# Generated by Django 3.2 on 2022-01-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_alter_students_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_admission',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_graduation',
            field=models.DateField(blank=True),
        ),
    ]
