# Generated by Django 3.2 on 2022-01-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20220114_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='DOB',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_admission',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_graduation',
            field=models.DateTimeField(blank=True),
        ),
    ]
