# Generated by Django 3.2 on 2022-01-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_auto_20220114_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='DOB',
            field=models.DateField(),
        ),
    ]
