# Generated by Django 3.2 on 2022-01-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_auto_20220114_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_graduation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
