# Generated by Django 3.2 on 2022-01-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_alter_students_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lectures',
            name='lec_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lectures',
            name='national_ID_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
