# Generated by Django 3.2 on 2022-01-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_auto_20220119_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='admission_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
