# Generated by Django 3.2 on 2022-01-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_auto_20220123_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks_yr1',
            name='stage',
            field=models.ForeignKey(blank=True, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.stages'),
        ),
        migrations.AlterField(
            model_name='marks_yr1',
            name='unit_or_subject_name',
            field=models.ForeignKey(blank=True, default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.units'),
        ),
    ]
