# Generated by Django 3.2 on 2022-01-23 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0038_alter_marks_yr1_unit_or_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks_yr7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('marks', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('stage', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.stages')),
                ('unit_or_subject_name', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.units')),
                ('user', models.ForeignKey(blank=True, max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='marks_yr6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('marks', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('stage', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.stages')),
                ('unit_or_subject_name', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.units')),
                ('user', models.ForeignKey(blank=True, max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='marks_yr5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('marks', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('stage', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.stages')),
                ('unit_or_subject_name', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.units')),
                ('user', models.ForeignKey(blank=True, max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='marks_yr4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('marks', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('stage', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.stages')),
                ('unit_or_subject_name', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.units')),
                ('user', models.ForeignKey(blank=True, max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='marks_yr3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('marks', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('stage', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.stages')),
                ('unit_or_subject_name', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.units')),
                ('user', models.ForeignKey(blank=True, max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='marks_yr2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('marks', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('stage', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.stages')),
                ('unit_or_subject_name', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.units')),
                ('user', models.ForeignKey(blank=True, max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
