# Generated by Django 3.2 on 2022-01-23 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0039_marks_yr2_marks_yr3_marks_yr4_marks_yr5_marks_yr6_marks_yr7'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('exams', models.CharField(blank=True, max_length=255, null=True)),
                ('co_ocurricular_activities', models.CharField(blank=True, max_length=255, null=True)),
                ('hostel_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('library_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('internet_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('electricity_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('food_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('furniture_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('water_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('stage', models.ForeignKey(blank=True, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.stages')),
                ('user', models.ForeignKey(blank=True, max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fee_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('date_paid', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
