# Generated by Django 3.2 on 2022-01-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0043_noticeboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stage', models.CharField(blank=True, max_length=5000, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('seat', models.CharField(blank=True, max_length=255, null=True)),
                ('votes', models.CharField(blank=True, max_length=5000, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
