# Generated by Django 3.2 on 2022-01-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0046_suggestionbox_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionbox',
            name='check',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='suggestionbox',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
