# Generated by Django 3.2 on 2022-01-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_auto_20220123_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialexam',
            old_name='date_paid',
            new_name='date_registered',
        ),
    ]
