# Generated by Django 3.2 on 2022-03-01 17:23

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_rename_date_paid_specialexam_date_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='lectures',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='students',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='fee_payment',
            name='bill_reference_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fee_payment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fee_payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='group',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('STAFF', 'STAFF'), ('SUPPLIERS', 'SUPPLIERS'), ('STUDENTS', 'STUDENTS'), ('LECTURERS', 'LECTURERS')], default='PUBLIC', max_length=255),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='school',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='co_ocurricular_activities',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='electricity_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='exams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='food_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='furniture_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='hostel_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='internet_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='library_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='water_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerunits',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='notice',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='specialexam',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='specialexam',
            name='unit_name',
            field=models.ForeignKey(blank=True, default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.units'),
        ),
        migrations.AlterField(
            model_name='suggestionbox',
            name='suggestion',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='voting',
            name='course',
            field=models.ForeignKey(blank=True, default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.programmes'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='stage',
            field=models.ForeignKey(blank=True, default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.stages'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AlterField(
            model_name='voting',
            name='seat',
            field=models.ForeignKey(blank=True, default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.seats'),
        ),
    ]
