# Generated by Django 3.2 on 2022-01-27 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_rename_date_paid_specialexam_date_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='co_ocurricular_activities',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='electricity_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='exams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='food_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='furniture_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='hostel_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='internet_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='library_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='water_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='specialexam',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='course',
            field=models.ForeignKey(blank=True, default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.programmes'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='stage',
            field=models.ForeignKey(blank=True, default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.stages'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='seat',
            field=models.ForeignKey(blank=True, default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.seats'),
        ),
    ]
