# Generated by Django 3.2 on 2022-03-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0049_auto_20220301_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='notice_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
