# Generated by Django 3.2 on 2022-01-27 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_auto_20220127_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialexam',
            name='unit_name',
            field=models.ForeignKey(blank=True, default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.units'),
        ),
    ]
