# Generated by Django 3.2 on 2022-02-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0051_alter_specialexam_unit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectures',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='students',
            name='profile_photo',
        ),
    ]
