# Generated by Django 3.2 on 2022-03-08 10:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0051_resit_exam_yr1_resit_exam_yr2_resit_exam_yr3_resit_exam_yr4_resit_exam_yr5_resit_exam_yr6_resit_exam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeeReceipt',
            new_name='FeeStructure',
        ),
    ]
