# Generated by Django 3.2 on 2022-03-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0052_rename_feereceipt_feestructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='user',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='program',
            field=models.ForeignKey(blank=True, default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='school.programmes'),
            preserve_default=False,
        ),
    ]
