# Generated by Django 3.2 on 2022-02-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0053_alter_faculty_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
