# Generated by Django 3.2 on 2022-02-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0054_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee_payment',
            name='bill_reference_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fee_payment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fee_payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
