# Generated by Django 3.2 on 2022-02-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0055_auto_20220213_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerunits',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
