# Generated by Django 3.2 on 2022-03-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0056_alter_lecturerunits_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='group',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('STAFF', 'STAFF'), ('SUPPLIERS', 'SUPPLIERS'), ('STUDENTS', 'STUDENTS'), ('LECTURERS', 'LECTURERS')], default='PUBLIC', max_length=255),
        ),
    ]
