# Generated by Django 3.2 on 2022-03-01 15:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0057_noticeboard_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='notice',
            field=ckeditor.fields.RichTextField(default='notice'),
        ),
    ]
