# Generated by Django 3.2 on 2022-03-01 15:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0058_alter_noticeboard_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionbox',
            name='suggestion',
            field=ckeditor.fields.RichTextField(default='suggestion'),
        ),
    ]
