# Generated by Django 3.2 on 2022-03-01 15:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0059_alter_suggestionbox_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='notice',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='suggestionbox',
            name='suggestion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
